# Generated by Django 5.0.6 on 2024-05-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="transaction_amount",
            field=models.FloatField(default=0.0),
        ),
    ]
