# Generated by Django 5.0.6 on 2024-05-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_transactionlog_current_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="transaction_amount_currency",
            field=models.CharField(
                choices=[
                    ("USD", "United States Dollar ($)"),
                    ("EUR", "Euro (€)"),
                    ("GBP", "British Pound Sterling (£)"),
                    ("CHF", "Swiss Franc (CHF)"),
                ],
                default="EUR",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="transactionlog",
            name="wallet_currency",
            field=models.CharField(
                choices=[
                    ("USD", "United States Dollar ($)"),
                    ("EUR", "Euro (€)"),
                    ("GBP", "British Pound Sterling (£)"),
                    ("CHF", "Swiss Franc (CHF)"),
                ],
                default="EUR",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="wallet",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "United States Dollar ($)"),
                    ("EUR", "Euro (€)"),
                    ("GBP", "British Pound Sterling (£)"),
                    ("CHF", "Swiss Franc (CHF)"),
                ],
                default="EUR",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="transactionlog",
            name="transaction_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="transactionlog",
            name="transaction_type",
            field=models.CharField(
                choices=[("debit", "Debit"), ("credit", "Credit")], max_length=10
            ),
        ),
    ]
