# Generated by Django 5.0.6 on 2024-05-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_transaction_transaction_amount_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="transaction_currency",
            field=models.CharField(
                choices=[
                    ("USD", "United States Dollar ($)"),
                    ("EUR", "Euro (€)"),
                    ("GBP", "British Pound Sterling (£)"),
                    ("CHF", "Swiss Franc (CHF)"),
                ],
                default="EUR",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_status",
            field=models.CharField(
                choices=[("success", "Success"), ("failed", "Failed")],
                default="success",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="transactionlog",
            name="transaction_currency",
            field=models.CharField(
                choices=[
                    ("USD", "United States Dollar ($)"),
                    ("EUR", "Euro (€)"),
                    ("GBP", "British Pound Sterling (£)"),
                    ("CHF", "Swiss Franc (CHF)"),
                ],
                default="EUR",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="transactionlog",
            name="transaction_status",
            field=models.CharField(
                choices=[("success", "Success"), ("failed", "Failed")],
                default="success",
                max_length=10,
            ),
        ),
    ]
