# Generated by Django 5.0.6 on 2024-05-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_transaction_transaction_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="current_balance",
            field=models.FloatField(default=0.0),
        ),
    ]
