# Generated by Django 5.0.6 on 2024-05-29 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_transaction_current_balance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="current_balance",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="transaction_currency",
        ),
        migrations.RemoveField(
            model_name="transactionlog",
            name="transaction_currency",
        ),
    ]
