# Generated by Django 5.0.6 on 2024-05-29 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_remove_transaction_current_balance_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="transaction_status",
        ),
        migrations.RemoveField(
            model_name="transactionlog",
            name="transaction_status",
        ),
    ]
