# Generated by Django 5.0.6 on 2024-05-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_remove_transaction_transaction_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="current_balance",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_currency",
            field=models.CharField(
                choices=[
                    ("USD", "United States Dollar ($)"),
                    ("EUR", "Euro (€)"),
                    ("GBP", "British Pound Sterling (£)"),
                    ("CHF", "Swiss Franc (CHF)"),
                ],
                default="EUR",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_status",
            field=models.CharField(
                choices=[("success", "Success"), ("failed", "Failed")],
                default="success",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="transactionlog",
            name="transaction_currency",
            field=models.CharField(
                choices=[
                    ("USD", "United States Dollar ($)"),
                    ("EUR", "Euro (€)"),
                    ("GBP", "British Pound Sterling (£)"),
                    ("CHF", "Swiss Franc (CHF)"),
                ],
                default="EUR",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="transactionlog",
            name="transaction_status",
            field=models.CharField(
                choices=[("success", "Success"), ("failed", "Failed")],
                default="success",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="transactionlog",
            name="current_balance",
            field=models.FloatField(),
        ),
    ]
