# Generated by Django 5.0.6 on 2024-05-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_transaction_current_balance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionlog",
            name="transaction_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
