# Generated by Django 5.0.6 on 2024-05-29 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_transactionlog_transaction_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactionlog",
            name="balance_before",
        ),
    ]
