# Generated by Django 5.0.6 on 2024-05-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_remove_transactionlog_balance_before"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="preferred_currency",
            field=models.CharField(
                choices=[
                    ("USD", "United States Dollar ($)"),
                    ("EUR", "Euro (€)"),
                    ("GBP", "British Pound Sterling (£)"),
                    ("CHF", "Swiss Franc (CHF)"),
                ],
                default="EUR",
                max_length=5,
            ),
        ),
    ]
