# Generated by Django 5.0.6 on 2024-05-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_transactionlog_converted_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="transaction_currency",
        ),
        migrations.AlterField(
            model_name="account",
            name="preferred_currency",
            field=models.CharField(default="EUR", max_length=5),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_amount_currency",
            field=models.CharField(default="EUR", max_length=5),
        ),
        migrations.AlterField(
            model_name="transactionlog",
            name="transaction_currency",
            field=models.CharField(default="EUR", max_length=5),
        ),
        migrations.AlterField(
            model_name="transactionlog",
            name="wallet_currency",
            field=models.CharField(default="EUR", max_length=5),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="currency",
            field=models.CharField(default="EUR", max_length=5),
        ),
    ]
